#!/bin/bash

set -ex

SCRIPT_DIR=`dirname $(readlink -f $0)`

source $SCRIPT_DIR/env-var


chpst -u $RUNAS:$RUNAS $MONGO_DIR/mongod --dbpath $DATA_DIR --noauth \
--pidfilepath $PIDFILE \
>>$LOG_DIR/mongo.pre-start.stderr.log 2>>$LOG_DIR/mongo.pre-start.stderr.log &
# create new admin user
sleep 5
$MONGO_DIR/mongo < $SCRIPT_DIR/../js/create_admin_user.js

echo $(cat $SCRIPT_DIR/../js/create_admin_user.js)>>$LOG_DIR/mongo.pre-start.stderr.log 2>>$LOG_DIR/mongo.pre-start.stderr.log &


if [ -f $PIDFILE ]; then
  kill -9 $(cat $PIDFILE)
  rm -f $PIDFILE
  sleep 1
fi
